linters:
  enable:
    - unused
    - misspell
    - errcheck
    - gosimple
    - staticcheck
    - revive
    - gofmt
    - gci
    - whitespace

linters-settings:
  unused: {}
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/felipe1496/open-wallet)
  whitespace:
    multi-if: true
    multi-func: true
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
