// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login/google": {
            "post": {
                "description": "Authenticates user with Google OAuth",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with Google",
                "operationId": "v1LoginWithGoogle",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_auth_handlers.LoginGoogleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User logged in",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_auth_handlers_LoginGoogleResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "List categories",
                "operationId": "v1ListCategories",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name:asc",
                        "description": "Sort field. \n- Allowed: name, created_at, id",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter expression. \n- Allowed fields \u0026 ops:\n  - color: eq, in\n  - created_at: eq, gt, gte, lt, lte\n  - id: eq, in\n  - name: eq, like, in\n  - user_id: eq, in\n",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "A category name to filter by",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of categories",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_categories_handlers_ListCategoriesResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Create a category",
                "operationId": "v1CreateCategory",
                "parameters": [
                    {
                        "description": "Category payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_categories_handlers.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Category created",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_categories_handlers_CreateCategoryResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/{category_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Delete Category By ID",
                "operationId": "v1DeleteCategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Category deleted"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Update Category By ID",
                "operationId": "v1UpdateCategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Category payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_categories_handlers.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_categories_handlers_UpdateCategoryResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/{period}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List categories with amount per period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "List categories with amount per period",
                "operationId": "v1ListCategoryAmountPerPeriod",
                "parameters": [
                    {
                        "type": "string",
                        "description": "period",
                        "name": "period",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter expression. \n- Allowed fields \u0026 ops:\n  - color: eq, in\n  - id: eq, in\n  - name: eq, like, in\n  - period: eq, in\n  - total_amount: eq, gt, gte, lt, lte\n  - user_id: eq, in\n",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name:asc",
                        "description": "Sort field. \n- Allowed: name, total_amount, period, id",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of categories with amount per period",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_categories_handlers_ListCategoryAmountPerPeriodResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/recurrences": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List user recurrences",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurrences"
                ],
                "summary": "List recurrences",
                "operationId": "v1ListRecurrences",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter expression. \n- Allowed fields \u0026 ops:\n  - amount: eq, gt, gte, lt, lte\n  - category_id: eq, in\n  - created_at: eq, gt, gte, lt, lte\n  - id: eq, in\n  - name: eq, like, in\n  - user_id: eq, in\n",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name:asc",
                        "description": "Sort field. \n- Allowed: name, created_at, id",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of recurrences",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_recurrences_handlers_ListRecurrencesResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new recurrence template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurrences"
                ],
                "summary": "Create a recurrence",
                "operationId": "v1CreateRecurrence",
                "parameters": [
                    {
                        "description": "Recurrence payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_recurrences_handlers.CreateRecurrenceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Recurrence created",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_recurrences_handlers_CreateRecurrenceResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/recurrences/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a recurrence template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurrences"
                ],
                "summary": "Delete Recurrence By ID",
                "operationId": "v1DeleteRecurrence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "recurrence ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "all",
                            "until_current"
                        ],
                        "type": "string",
                        "default": "all",
                        "description": "Handling of linked transactions: 'all' (default) deletes the recurrence and all related transactions (past/future); 'until_current' preserves past history but removes future recurrences.",
                        "name": "scope",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Recurrence deleted"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a recurrence template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurrences"
                ],
                "summary": "Update a recurrence",
                "operationId": "v1UpdateRecurrence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "recurrence ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recurrence payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_recurrences_handlers.UpdateRecurrenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recurrence updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_recurrences_handlers_UpdateRecurrenceResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/recurrences/{period}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates entry records for all recurrence templates that don't already have one in the given period.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurrences"
                ],
                "summary": "Prepare recurrences for a period",
                "operationId": "v1PrepareRecurrence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Period in YYYYMM format (e.g. 202603)",
                        "name": "period",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Recurrences prepared"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a transaction with all of it entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a transaction",
                "operationId": "v1CreateTransaction",
                "parameters": [
                    {
                        "description": "Transaction payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_transactions_handlers.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Installment updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_transactions_handlers_CreateTransactionResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/entries": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List a detailed view of entries joined with transactions for a given period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List entries",
                "operationId": "v1ListEntries",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter expression. \n- Allowed fields \u0026 ops:\n  - amount: eq, gt, gte, lt, lte\n  - category_id: eq, in\n  - created_at: eq, gt, gte, lt, lte\n  - id: eq, in\n  - period: eq, in, gte, lte\n  - reference_date: eq, gt, gte, lt, lte\n  - type: eq, in\n  - user_id: eq, in\n",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "reference_date:asc",
                        "description": "Sort field. \n- Allowed: reference_date, amount, id, created_at",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of entries",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_transactions_handlers_ListEntriesResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns total income, expense and balance for each month in the specified period range.\nREQUIRED: period gte 'YYYYMM' and period lte 'YYYYMM' (max 12 months range)\nNote: Only periods with existing transactions/entries will be returned.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get financial summary grouped by month",
                "operationId": "v1GetSummary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter expression. \n- Allowed fields \u0026 ops:\n  - period: eq, in, gte, lte\n  - total_balance: eq, gt, gte, lt, lte\n  - total_expense: eq, gt, gte, lt, lte\n  - total_income: eq, gt, gte, lt, lte\n",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "period:asc",
                        "description": "Sort field. \n- Allowed: period, total_expense, total_income, total_balance",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Summary data",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_transactions_handlers_SummaryResponseData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/{transaction_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a transaction and all entries related by the ID of the transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Delete Transaction By ID",
                "operationId": "v1DeleteTransaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "transaction ID",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Transaction deleted"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Update a transaction",
                "operationId": "v1UpdateTransaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "transaction ID",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Installment payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_resources_transactions_handlers.UpdateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Installment updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_transactions_handlers_UpdateTransactionResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_felipe1496_open-wallet_internal_resources_transactions_repository.TransactionType": {
            "type": "string",
            "enum": [
                "simple_expense",
                "income",
                "installment",
                "recurrence"
            ],
            "x-enum-varnames": [
                "SimpleExpense",
                "Income",
                "Installment",
                "Recurrence"
            ]
        },
        "github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_categories_handlers_ListCategoriesResponseData": {
            "type": "object",
            "required": [
                "data",
                "query"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_categories_handlers.ListCategoriesResponseData"
                },
                "query": {
                    "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_querybuilder.Metadata"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_categories_handlers_ListCategoryAmountPerPeriodResponseData": {
            "type": "object",
            "required": [
                "data",
                "query"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_categories_handlers.ListCategoryAmountPerPeriodResponseData"
                },
                "query": {
                    "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_querybuilder.Metadata"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_recurrences_handlers_ListRecurrencesResponseData": {
            "type": "object",
            "required": [
                "data",
                "query"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_recurrences_handlers.ListRecurrencesResponseData"
                },
                "query": {
                    "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_querybuilder.Metadata"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.PaginatedResponse-internal_resources_transactions_handlers_ListEntriesResponseData": {
            "type": "object",
            "required": [
                "data",
                "query"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_transactions_handlers.ListEntriesResponseData"
                },
                "query": {
                    "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_querybuilder.Metadata"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_auth_handlers_LoginGoogleResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_auth_handlers.LoginGoogleResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_categories_handlers_CreateCategoryResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_categories_handlers.CreateCategoryResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_categories_handlers_UpdateCategoryResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_categories_handlers.UpdateCategoryResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_recurrences_handlers_CreateRecurrenceResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_recurrences_handlers.CreateRecurrenceResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_recurrences_handlers_UpdateRecurrenceResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_recurrences_handlers.UpdateRecurrenceResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_transactions_handlers_CreateTransactionResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_transactions_handlers.CreateTransactionResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_transactions_handlers_SummaryResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_transactions_handlers.SummaryResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util.ResponseData-internal_resources_transactions_handlers_UpdateTransactionResponseData": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_resources_transactions_handlers.UpdateTransactionResponseData"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util_httputil.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_util_httputil.HTTPErrorData"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util_httputil.HTTPErrorData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_felipe1496_open-wallet_internal_util_querybuilder.Metadata": {
            "type": "object",
            "required": [
                "next_page",
                "page",
                "per_page",
                "total_items",
                "total_pages"
            ],
            "properties": {
                "next_page": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_resources_auth_handlers.LoginGoogleRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "internal_resources_auth_handlers.LoginGoogleResponseData": {
            "type": "object",
            "required": [
                "access_token",
                "user"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/internal_resources_auth_handlers.UserResource"
                }
            }
        },
        "internal_resources_auth_handlers.UserResource": {
            "type": "object",
            "required": [
                "avatar_url",
                "created_at",
                "email",
                "id",
                "name"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_resources_categories_handlers.CategoryAmountPerPeriodResource": {
            "type": "object",
            "required": [
                "color",
                "id",
                "name",
                "total_amount"
            ],
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "internal_resources_categories_handlers.CategoryResource": {
            "type": "object",
            "required": [
                "color",
                "created_at",
                "id",
                "name",
                "user_id"
            ],
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_resources_categories_handlers.CreateCategoryRequest": {
            "type": "object",
            "required": [
                "color",
                "name"
            ],
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_resources_categories_handlers.CreateCategoryResponseData": {
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "$ref": "#/definitions/internal_resources_categories_handlers.CategoryResource"
                }
            }
        },
        "internal_resources_categories_handlers.ListCategoriesResponseData": {
            "type": "object",
            "required": [
                "categories"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_resources_categories_handlers.CategoryResource"
                    }
                }
            }
        },
        "internal_resources_categories_handlers.ListCategoryAmountPerPeriodResponseData": {
            "type": "object",
            "required": [
                "categories"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_resources_categories_handlers.CategoryAmountPerPeriodResource"
                    }
                }
            }
        },
        "internal_resources_categories_handlers.UpdateCategoryRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "internal_resources_categories_handlers.UpdateCategoryResponseData": {
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "$ref": "#/definitions/internal_resources_categories_handlers.CategoryResource"
                }
            }
        },
        "internal_resources_recurrences_handlers.CreateRecurrenceRequest": {
            "type": "object",
            "required": [
                "amount",
                "day_of_month",
                "name",
                "start_period"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "string"
                },
                "day_of_month": {
                    "type": "integer",
                    "maximum": 31,
                    "minimum": 1
                },
                "end_period": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "note": {
                    "type": "string",
                    "maxLength": 400,
                    "minLength": 0
                },
                "start_period": {
                    "type": "string"
                }
            }
        },
        "internal_resources_recurrences_handlers.CreateRecurrenceResponseData": {
            "type": "object",
            "required": [
                "recurrence"
            ],
            "properties": {
                "recurrence": {
                    "$ref": "#/definitions/internal_resources_recurrences_handlers.RecurrenceResource"
                }
            }
        },
        "internal_resources_recurrences_handlers.ListRecurrencesResponseData": {
            "type": "object",
            "required": [
                "recurrences"
            ],
            "properties": {
                "recurrences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_resources_recurrences_handlers.RecurrenceResource"
                    }
                }
            }
        },
        "internal_resources_recurrences_handlers.RecurrenceResource": {
            "type": "object",
            "required": [
                "amount",
                "created_at",
                "day_of_month",
                "id",
                "name",
                "start_period",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_color": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "day_of_month": {
                    "type": "integer"
                },
                "end_period": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "start_period": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_resources_recurrences_handlers.UpdateRecurrenceRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "string"
                },
                "day_of_month": {
                    "type": "integer",
                    "maximum": 31,
                    "minimum": 1
                },
                "end_period": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "note": {
                    "type": "string",
                    "maxLength": 400,
                    "minLength": 0
                },
                "start_period": {
                    "type": "string"
                }
            }
        },
        "internal_resources_recurrences_handlers.UpdateRecurrenceResponseData": {
            "type": "object",
            "required": [
                "recurrence"
            ],
            "properties": {
                "recurrence": {
                    "$ref": "#/definitions/internal_resources_recurrences_handlers.RecurrenceResource"
                }
            }
        },
        "internal_resources_transactions_handlers.CreateEntryRequest": {
            "type": "object",
            "required": [
                "amount",
                "reference_date"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "maximum": 999999,
                    "minimum": -999999
                },
                "reference_date": {
                    "type": "string"
                }
            }
        },
        "internal_resources_transactions_handlers.CreateTransactionRequest": {
            "type": "object",
            "required": [
                "entries",
                "name",
                "type"
            ],
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_resources_transactions_handlers.CreateEntryRequest"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "note": {
                    "type": "string",
                    "maxLength": 400,
                    "minLength": 0
                },
                "type": {
                    "enum": [
                        "installment",
                        "simple_expense",
                        "income"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_felipe1496_open-wallet_internal_resources_transactions_repository.TransactionType"
                        }
                    ]
                }
            }
        },
        "internal_resources_transactions_handlers.CreateTransactionResponseData": {
            "type": "object",
            "required": [
                "transaction"
            ],
            "properties": {
                "transaction": {
                    "$ref": "#/definitions/internal_resources_transactions_handlers.TransactionResource"
                }
            }
        },
        "internal_resources_transactions_handlers.EntryResource": {
            "type": "object",
            "required": [
                "amount",
                "created_at",
                "id",
                "installment",
                "name",
                "period",
                "reference_date",
                "total_amount",
                "total_installments",
                "transaction_id",
                "type",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_color": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "installment": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                },
                "recurrence_id": {
                    "type": "string"
                },
                "reference_date": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "total_installments": {
                    "type": "integer"
                },
                "transaction_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_resources_transactions_handlers.ListEntriesResponseData": {
            "type": "object",
            "required": [
                "entries"
            ],
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_resources_transactions_handlers.EntryResource"
                    }
                }
            }
        },
        "internal_resources_transactions_handlers.MonthlySummaryResource": {
            "type": "object",
            "required": [
                "balance",
                "expense",
                "income",
                "period"
            ],
            "properties": {
                "balance": {
                    "type": "number"
                },
                "expense": {
                    "type": "number"
                },
                "income": {
                    "type": "number"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "internal_resources_transactions_handlers.SummaryResponseData": {
            "type": "object",
            "required": [
                "summary"
            ],
            "properties": {
                "summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_resources_transactions_handlers.MonthlySummaryResource"
                    }
                }
            }
        },
        "internal_resources_transactions_handlers.TransactionResource": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "type",
                "user_id"
            ],
            "properties": {
                "category_color": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "recurrence_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_resources_transactions_handlers.UpdateEntryRequest": {
            "type": "object",
            "required": [
                "amount",
                "reference_date"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "maximum": 999999,
                    "minimum": -999999
                },
                "reference_date": {
                    "type": "string"
                }
            }
        },
        "internal_resources_transactions_handlers.UpdateTransactionRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_resources_transactions_handlers.UpdateEntryRequest"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "note": {
                    "type": "string",
                    "maxLength": 400,
                    "minLength": 0
                }
            }
        },
        "internal_resources_transactions_handlers.UpdateTransactionResponseData": {
            "type": "object",
            "required": [
                "transaction"
            ],
            "properties": {
                "transaction": {
                    "$ref": "#/definitions/internal_resources_transactions_handlers.TransactionResource"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Open Wallet API",
	Description:      "This is the Open Wallet API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
